### ISSUE TITLE
The prompt block renders code the kernel refuses: a `self` parameter kills the whole block, and three of four reservations are not mirrored

### ISSUE THREAD

**Issue by CNSeniorious000** [CNSeniorious000/dsh-py-codeact#12]
Two independent ways `renderToolsSection` hands the model Python that does not work. Both reproduced against the real renderer at `3c0195f`.

### A tool parameter named `self` makes the entire block uncompilable

`method()` splices `self` into the Protocol stub without checking it against the tool's own parameter names:

```python
class _McpSrv(Protocol):
    async def list(self, *, self: str) -> Any: ...
    async def other(self, *, q: str) -> Any: ...
```

```
SyntaxError: duplicate argument 'self' in function definition
```

One tool takes down every sibling stub **and** every native signature below it — the whole fenced block. `isUsableName` accepts `self` because it is a valid identifier; nothing checks it against the name the stub reserves. This is the failure class `renderToolsSection`'s own comments say it was hardened against (`class`, `file-path`, keyword names), one level in.

The existing `parses()` cases never declare a parameter named `self`, so the suite is green.

### `toolSpecs` mirrors one of the kernel's four reservations

`lib/index.js` filters `schema.name !== 'mcp'`. `build_bindings` also refuses `ToolCallError`, every `_`-leading name, and everything in `vars(ToolsModule) | vars(types.ModuleType)`. Rendered for a catalogue with natives named `ToolCallError` and `_private`:

```python
from typing import Any
from __dsh__.tools import ToolCallError, ToolCallError, _private, read

async def ToolCallError() -> Any: ...
async def _private() -> Any: ...
async def read() -> Any: ...
```

The kernel binds only `['read']`. Copying that line raises `ImportError: cannot import name '_private'`. And the duplicated second `ToolCallError` silently resolves to the exception class the instructions tell the model to catch — so `await ToolCallError(q=…)` raises a `TypeError` it has no way to explain.

The `toolSpecs` comment records that the `mcp` reservation was mirrored there deliberately "rather than at the render". The other three were never carried across.

### `ToolCallError` is in neither listing

```
("ToolCallError" in dir(T), hasattr(T, "ToolCallError"), "ToolCallError" in T.__all__)
-> (False, True, False)
```

So `from __dsh__.tools import *` then `except ToolCallError:` -> `NameError: name 'ToolCallError' is not defined`. The block puts `ToolCallError` first in its import line precisely so the natural `except` clause resolves; a model that reaches for `import *` instead loses the failure path it was told to catch. Pre-existing, and adjacent enough to the two above to fix in the same pass.

**Comment by CNSeniorious000** [comment]
All three fixed in `c2a8671`, verified against `main` just now rather than assumed — and bisected to place the fix, since I had first credited the wrong commit:

```
1f21440   self -> SyntaxError: duplicate argument 'self'   | import -> from __dsh__.tools import ToolCallError, ToolCallError, _private, read
c2a8671   self -> compiles                                 | import -> from __dsh__.tools import ToolCallError, read
5518478   self -> compiles                                 | import -> from __dsh__.tools import ToolCallError, read
```

**A — a parameter named `self`.** Nothing splices `self` any more: the `Protocol` stubs were replaced by module listings, so a server's tools are rendered as call-site comments and the name is just a parameter.

```python
# mcp.srv.list(*, self: str) -> Any
```

**B — the reservations.** `RESERVED_NAMES` plus the `_`-leading filter now mirror the whole of `build_bindings`. The duplicate `ToolCallError` and the unbindable `_private` are both gone from the import line.

**C — `ToolCallError` and star-import.** The triple from the issue now reads:

```
("ToolCallError" in dir(T), hasattr(T, "ToolCallError"), "ToolCallError" in T.__all__)
-> (False, True, True)          # was (False, True, False)

from __dsh__.tools import *; ToolCallError
-> <class '__main__.ToolCallError'>
```

`dir()` still omits it, and that stays deliberate — it is not a tool, so it does not belong in a listing of them. `__all__` is what star-import *binds*, which is the half the failure path needed.

Note the first row: **published 0.2.3 (`1f21440`) still carries A and B.** Both are on `main` unreleased.
